/* Minimal public Win32 declarations. All integer widths match the x64 ABI. */
typedef unsigned short WCHAR;typedef void*HANDLE;typedef HANDLE HWND;typedef HANDLE HINSTANCE;
typedef unsigned int UINT,DWORD;typedef int BOOL;typedef unsigned long long SIZE_T,WPARAM;typedef long long LPARAM,LRESULT;
typedef LRESULT(*WNDPROC)(HWND,UINT,WPARAM,LPARAM);
typedef struct{int x,y;}POINT;typedef struct{int left,top,right,bottom;}RECT;
typedef struct{UINT style;WNDPROC proc;int clsExtra,wndExtra;HINSTANCE instance;HANDLE icon,cursor,background;const WCHAR*menu,*name;}WNDCLASSW;
typedef struct{HWND hwnd;UINT message;WPARAM wParam;LPARAM lParam;DWORD time;POINT pt;DWORD privateValue;}MSG;
typedef struct{DWORD size;HWND owner;HINSTANCE instance;const WCHAR*filter;WCHAR*customFilter;DWORD maxCustomFilter,filterIndex;WCHAR*file;DWORD maxFile;WCHAR*fileTitle;DWORD maxFileTitle;const WCHAR*initialDir,*title;DWORD flags;unsigned short fileOffset,fileExtension;const WCHAR*defExt;LPARAM custData;void*hook;const WCHAR*templateName;void*reserved;DWORD reservedWord,flagsEx;}OPENFILENAMEW;
extern HINSTANCE GetModuleHandleW(const WCHAR*);extern HANDLE GetProcessHeap(void);extern void*HeapAlloc(HANDLE,DWORD,SIZE_T);extern void*HeapReAlloc(HANDLE,DWORD,void*,SIZE_T);extern BOOL HeapFree(HANDLE,DWORD,void*);extern void ExitProcess(UINT);
extern HANDLE CreateFileW(const WCHAR*,DWORD,DWORD,void*,DWORD,DWORD,HANDLE);extern BOOL ReadFile(HANDLE,void*,DWORD,DWORD*,void*);extern BOOL WriteFile(HANDLE,const void*,DWORD,DWORD*,void*);extern BOOL CloseHandle(HANDLE);extern BOOL GetFileSizeEx(HANDLE,long long*);extern BOOL DeleteFileW(const WCHAR*);extern BOOL MoveFileExW(const WCHAR*,const WCHAR*,DWORD);extern BOOL FlushFileBuffers(HANDLE);extern int MultiByteToWideChar(UINT,DWORD,const char*,int,WCHAR*,int);extern int WideCharToMultiByte(UINT,DWORD,const WCHAR*,int,char*,int,const char*,BOOL*);extern DWORD GetLastError(void);
extern unsigned short RegisterClassW(const WNDCLASSW*);extern HWND CreateWindowExW(DWORD,const WCHAR*,const WCHAR*,DWORD,int,int,int,int,HWND,HANDLE,HINSTANCE,void*);extern LRESULT DefWindowProcW(HWND,UINT,WPARAM,LPARAM);extern BOOL ShowWindow(HWND,int);extern BOOL UpdateWindow(HWND);extern BOOL GetMessageW(MSG*,HWND,UINT,UINT);extern BOOL TranslateMessage(const MSG*);extern LRESULT DispatchMessageW(const MSG*);extern void PostQuitMessage(int);extern LRESULT SendMessageW(HWND,UINT,WPARAM,LPARAM);extern BOOL SetWindowTextW(HWND,const WCHAR*);extern int GetWindowTextW(HWND,WCHAR*,int);extern int GetWindowTextLengthW(HWND);extern int MessageBoxW(HWND,const WCHAR*,const WCHAR*,UINT);extern HANDLE LoadCursorW(HINSTANCE,const WCHAR*);extern BOOL MoveWindow(HWND,int,int,int,int,BOOL);extern BOOL GetClientRect(HWND,RECT*);extern BOOL EnableWindow(HWND,BOOL);extern BOOL PeekMessageW(MSG*,HWND,UINT,UINT,UINT);extern BOOL SetProcessDPIAware(void);extern BOOL DestroyWindow(HWND);
extern HANDLE CreateFontW(int,int,int,int,int,DWORD,DWORD,DWORD,DWORD,DWORD,DWORD,DWORD,DWORD,const WCHAR*);extern BOOL DeleteObject(HANDLE);extern BOOL GetOpenFileNameW(OPENFILENAMEW*);extern BOOL GetSaveFileNameW(OPENFILENAMEW*);
#define W(x) ((const WCHAR*)L##x)
extern DWORD GetFileAttributesW(const WCHAR*);
